"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { demoReviewed, type CompanyDemo, type DemoAccount } from "../lib/company-demos";

type View = "Overview" | "Market" | "ICP" | "Accounts" | "Priority Accounts" | "Pipeline" | "Campaigns" | "Messaging" | "Insights";
function Card({ label, title, children }: { label: string; title: string; children: ReactNode }) {
  return <section className="workspace-card research-card"><div className="card-heading"><div><span>{label}</span><h2>{title}</h2></div></div>{children}</section>;
}
function Sources({ demo, ids }: { demo: CompanyDemo; ids: string[] }) {
  return <div className="research-source-links">{ids.map((id) => { const item = demo.sources.find((s) => s.id === id)!; return <a key={id} href={item.url} target="_blank" rel="noreferrer">{item.publisher}: {item.title} ↗</a>; })}</div>;
}
function Title({ demo, title, description }: { demo: CompanyDemo; title: string; description: string }) {
  return <div className="page-title"><div><span>{demo.name.toUpperCase()} / RESEARCHED GTM PLAN</span><h1>{title}</h1><p>{description}</p></div><span className="research-badge">Sourced case study</span></div>;
}
function useDialog(close: () => void) {
  const ref = useRef<HTMLElement>(null);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const node = ref.current;
    node?.querySelector<HTMLElement>("button, a")?.focus();
    const overflow = document.body.style.overflow; document.body.style.overflow = "hidden";
    const key = (event: KeyboardEvent) => {
      if (event.key === "Escape") { event.preventDefault(); close(); }
      if (event.key === "Tab") {
        const items = [...(node?.querySelectorAll<HTMLElement>("button, a[href], input, select, textarea, summary, [tabindex='0']") ?? [])];
        const first = items[0]; const last = items.at(-1);
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
        else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
      }
    };
    document.addEventListener("keydown", key);
    return () => { document.removeEventListener("keydown", key); document.body.style.overflow = overflow; previous?.focus(); };
  }, [close]);
  return ref;
}
export function CompanyResearchSources({ demo, close }: { demo: CompanyDemo; close: () => void }) {
  const ref = useDialog(close);
  return <div className="provenance-backdrop"><button className="provenance-dismiss" onClick={close} aria-label="Close company sources" /><section ref={ref} className="provenance-modal company-source-modal" role="dialog" aria-modal="true" aria-labelledby="company-source-title"><header><div><span>PUBLIC SOURCES / RESEARCH LIMITS</span><h2 id="company-source-title">{demo.name}: evidence behind the plan</h2></div><button onClick={close} aria-label="Close company sources">×</button></header><div className="company-source-body"><p>Reviewed {demoReviewed}. This is a dated, manually researched snapshot. GTM Lab is an independent portfolio demo and is not affiliated with {demo.name}.</p><p>{demo.limits}</p><p>Facts link to public sources. Market choices, buyer roles, account sequencing, campaigns and drafts are editorial proposals. Intent, private pipeline, revenue and campaign results are unknown. Some source pages only exposed publisher search excerpts; those limitations are recorded below.</p><ol>{demo.sources.map((item) => <li key={item.id}><a href={item.url} target="_blank" rel="noreferrer"><strong>{item.title} ↗</strong></a><span>{item.publisher} · {item.date} · reviewed {demoReviewed}</span>{item.note && <p>{item.note}</p>}</li>)}</ol></div></section></div>;
}
function AccountBrief({ demo, account, close }: { demo: CompanyDemo; account: DemoAccount; close: () => void }) {
  const ref = useDialog(close);
  return <div className="provenance-backdrop"><button className="provenance-dismiss" onClick={close} aria-label="Close company account brief" /><section ref={ref} className="provenance-modal company-account-modal" role="dialog" aria-modal="true" aria-labelledby="company-account-title"><header><div><span>REAL ORGANIZATION / PROPOSED ACCOUNT PLAN</span><h2 id="company-account-title">{account.company}</h2></div><button onClick={close} aria-label="Close company account brief">×</button></header><div className="company-source-body"><span className="research-badge">{account.relationship}</span><h3>Published evidence</h3><p>{account.fact}</p><Sources demo={demo} ids={[account.sourceId]} /><h3>Why investigate · hypothesis</h3><p>{account.why}</p><div className="research-priority-grid"><div><h3>Proposed buyer</h3><p>{account.buyer}</p><small>Role hypothesis, not a verified named contact.</small></div><div><h3>Question to validate</h3><p>{account.question}</p></div></div><h3>Constraint to resolve</h3><p>{account.constraint}</p><h3>Next action · proposed</h3><p>{account.action}</p><details className="inline-details"><summary>Draft a conversation starter</summary><p className="research-note">Unsent draft · proposed angle · no claimed results or commitments.</p><div className="research-copy"><p>Hi [verified owner],</p><p>We reviewed your public {account.segment.toLowerCase()} context. {account.angle}</p><p>{account.question}</p><p>Would a short scoping conversation be useful, or is another team responsible?</p></div></details><p className="research-note">Current intent, additional budget and sales stage remain unknown.</p></div></section></div>;
}
function PriorityCard({ demo, account, index, open }: { demo: CompanyDemo; account: DemoAccount; index: number; open: () => void }) {
  return <article className="priority-account"><div className="priority-rank"><span>Priority</span><b>{String(index + 1).padStart(2, "0")}</b></div><div className="priority-main"><div className="priority-company"><div><span>{account.segment}</span><h2>{account.company}</h2></div><span className="priority-editorial">Editorial focus</span></div><p className="company-relationship">{account.relationship}</p><div className="priority-evidence"><small>PUBLISHED EVIDENCE</small><p>{account.fact}</p><Sources demo={demo} ids={[account.sourceId]} /></div><div className="research-priority-grid"><div><small>WHY THIS ACCOUNT · HYPOTHESIS</small><p>{account.why}</p></div><div><small>PROPOSED BUYER</small><p>{account.buyer}</p></div></div><div className="priority-actions"><div><small>NEXT ACTION</small><p>{account.action}</p></div><div><small>VALIDATE FIRST</small><p>{account.constraint}</p></div><button onClick={open}>Open account brief →</button></div></div></article>;
}
function Accounts({ demo, priority, setView, open }: { demo: CompanyDemo; priority: boolean; setView: (view: View) => void; open: (account: DemoAccount) => void }) {
  const [search, setSearch] = useState("");
  const filtered = demo.accounts.filter((a) => `${a.company} ${a.segment}`.toLowerCase().includes(search.toLowerCase()));
  if (priority) return <><Title demo={demo} title="Two accounts. A clear next move." description="A focused editorial shortlist from the full account list. Public evidence informs the choices; the strategy and actions are proposals." /><div className="priority-list-heading"><span>2 priorities · {demo.accounts.length} researched accounts</span><button className="link-button" onClick={() => setView("Accounts")}>View all accounts →</button></div><div className="priority-stack research-priority-stack">{demo.accounts.slice(0, 2).map((a, i) => <PriorityCard demo={demo} account={a} index={i} open={() => open(a)} key={a.id} />)}</div><details className="inline-details"><summary>Why these two?</summary><p className="company-prose">{demo.ranking}</p></details></>;
  return <><Title demo={demo} title="Real organizations. Clear relationship context." description={demo.limits} /><div className="filter-bar research-filters"><label className="search-field"><input aria-label="Search company accounts" placeholder="Search organization or segment" value={search} onChange={(e) => setSearch(e.target.value)} /></label><span>{filtered.length} of {demo.accounts.length} accounts</span></div><section className="workspace-card research-table-wrap"><table className="research-table"><caption>Researched account context · private intent, budget and stage unknown</caption><thead><tr><th>Organization</th><th>Published evidence</th><th>Relationship context</th><th>Action</th></tr></thead><tbody>{filtered.map((a) => <tr key={a.id}><td><strong>{a.company}</strong><small>{a.segment}</small></td><td><p>{a.fact}</p><Sources demo={demo} ids={[a.sourceId]} /></td><td>{a.relationship}</td><td><button className="primary-small" onClick={() => open(a)}>Open brief →</button></td></tr>)}</tbody></table>{!filtered.length && <div className="research-empty"><p>No matching accounts.</p><button className="link-button" onClick={() => setSearch("")}>Clear search</button></div>}</section></>;
}
export default function CompanyResearchWorkspace({ demo, view, setView, openSources }: { demo: CompanyDemo; view: View; setView: (view: View) => void; openSources: () => void }) {
  const [selected, setSelected] = useState<DemoAccount | null>(null);
  return <div className="research-workspace company-demo-workspace"><div className="research-banner"><div><strong>Public evidence + proposed strategy</strong><span>Reviewed {demoReviewed} · independent portfolio case · private operating metrics unknown</span></div><button onClick={openSources}>Sources & limits ↗</button></div>
    {view === "Overview" && <><Title demo={demo} title={demo.headline} description={demo.subtitle + ". A sourced company brief and a focused commercial proposal."} /><div className="dashboard-grid overview-lead"><Card label="SOURCED COMPANY CONTEXT" title={`What ${demo.name} sells`}><p className="overview-summary">{demo.summary}</p><Sources demo={demo} ids={demo.companySources} /><dl className="overview-facts"><div><dt>Target customer</dt><dd>{demo.customer}</dd></div><div><dt>Proposed starting focus</dt><dd>{demo.focus}</dd></div></dl><button className="link-button" onClick={() => setView("Market")}>Explore the market choice →</button></Card><Card label="PROPOSED COMMERCIAL THESIS" title="A focused route to the next decision"><p className="overview-summary">{demo.thesis}</p><ol className="recommendations">{demo.recommendations.map((item, i) => <li key={item}><b>{String(i + 1).padStart(2, "0")}</b><span>{item}</span></li>)}</ol></Card></div><div className="overview-section-heading"><div><span>RESEARCH SNAPSHOT</span><h2>Evidence first. Private results stay unknown.</h2></div></div><div className="metric-grid overview-metrics"><div className="metric-card"><span>Researched accounts</span><strong>{demo.accounts.length}</strong><small>Real organizations · explicit relationship context</small></div><div className="metric-card"><span>Priority focus</span><strong>2</strong><small>Editorial sequence · no invented scores</small></div><div className="metric-card"><span>Private pipeline / revenue</span><strong>Unknown</strong><small>No CRM or private operating data</small></div></div><details className="overview-details"><summary><span>Two accounts to focus on</span><small>Evidence, fit reasoning and practical next steps</small></summary><div className="priority-stack research-priority-stack">{demo.accounts.slice(0, 2).map((a, i) => <PriorityCard demo={demo} account={a} index={i} open={() => setSelected(a)} key={a.id} />)}</div></details></>}
    {view === "Market" && <><Title demo={demo} title="Choose a market you can explain." description="Proposed sequencing, grounded in the public context. No invented TAM, segment counts or market-growth estimates." /><div className="research-segment-grid">{demo.markets.map((m) => <Card label="PROPOSED MARKET CHOICE" title={m.name} key={m.name}><p>{m.rationale}</p><h3>Tradeoff to validate</h3><p>{m.tradeoff}</p></Card>)}</div><Card label="PUBLIC BASIS" title="Sources behind the market context"><Sources demo={demo} ids={demo.companySources} /><p>{demo.limits}</p></Card></>}
    {view === "ICP" && <><Title demo={demo} title="Define the conditions for a good fit." description="Fit criteria and buying roles are hypotheses to validate with the actual relationship owner." /><div className="research-segment-grid">{demo.icp.map((c) => <Card label="PROPOSED QUALIFICATION" title={c.title} key={c.title}><ul>{c.items.map((item) => <li key={item}>{item}</li>)}</ul></Card>)}</div><div className="research-segment-grid">{demo.buyers.map((b) => <Card label="PROPOSED ROLE / NO NAMED CONTACT" title={b.role} key={b.role}><p>{b.responsibility}</p><h3>Question to validate</h3><p>{b.question}</p></Card>)}</div></>}
    {(view === "Accounts" || view === "Priority Accounts") && <Accounts key={`${demo.id}-${view}`} demo={demo} priority={view === "Priority Accounts"} setView={setView} open={setSelected} />}
    {view === "Pipeline" && <><Title demo={demo} title="Qualify the next step before forecasting." description="A proposed commercial workflow. Public relationships and announcements do not establish incremental pipeline or recognized revenue." /><div className="research-unknowns">{["Private pipeline", "Additional budget", "Win probability", "Current sales stage"].map((label) => <div key={label}><span>{label}</span><strong>Unknown</strong><small>Requires validated internal data</small></div>)}</div><Card label="PROPOSED EXECUTION / NO FABRICATED STAGES" title="A path to an accepted commercial decision">{demo.steps.map((step, i) => <div className="research-process-step" key={step.stage}><b>0{i + 1}</b><div><h3>{step.stage}</h3><p>{step.exit}</p></div></div>)}</Card><Card label="MEASURE WHEN DATA EXISTS" title="Agree on evidence before launch"><ul>{demo.measures.map((m) => <li key={m}>{m}</li>)}</ul><p>No measurement results are claimed here.</p></Card></>}
    {view === "Campaigns" && <><Title demo={demo} title="Design a focused commercial test." description="Proposed programs, not campaigns already run. Budgets, responses, conversion and ROI are not invented." /><div className="dashboard-grid">{demo.campaigns.map((c) => <Card key={c.title} label="PROPOSED / NOT RUN" title={c.title}><h3>{c.channel}</h3><p>{c.action}</p><h3>What would make it useful?</h3><p>{c.measure}</p></Card>)}</div></>}
    {view === "Messaging" && <><Title demo={demo} title="Lead with a relevant question." description="Account-specific, unsent drafts based on public evidence. Validate ownership and context before use." /><div className="dashboard-grid">{demo.accounts.slice(0, 2).map((a) => <Card key={a.id} label="UNSENT DRAFT / PROPOSED ANGLE" title={a.company}><p className="company-relationship">{a.relationship}</p><div className="research-copy"><p>Hi [verified owner],</p><p>{a.angle}</p><p>{a.question}</p><p>Would a short scoping conversation be useful?</p></div><h3>Before using this draft</h3><p>{a.constraint}</p><Sources demo={demo} ids={[a.sourceId]} /><button className="link-button" onClick={() => setSelected(a)}>Open full account context →</button></Card>)}</div></>}
    {view === "Insights" && <><Title demo={demo} title="The decisions that make this plan useful." description="Editorial conclusions and next actions. These are strategic hypotheses, not measured company outcomes." />{demo.insights.map((item) => <Card key={item.title} label="STRATEGIC INTERPRETATION" title={item.title}><p>{item.why}</p><h3>Next action</h3><p>{item.action}</p></Card>)}<Card label="WHAT WE STILL NEED" title="Validate the operating reality"><p>{demo.limits}</p><button className="link-button" onClick={openSources}>Review sources and limits →</button></Card></>}
    {selected && <AccountBrief demo={demo} account={selected} close={() => setSelected(null)} />}
  </div>;
}
