import type { GTMPlan } from "./types";

export type CompanyDemoId = "nike" | "decagon" | "anduril";
export type DemoSource = { id: string; title: string; publisher: string; url: string; date: string; note?: string };
export type DemoAccount = { id: string; company: string; segment: string; relationship: string; fact: string; sourceId: string; why: string; buyer: string; action: string; constraint: string; question: string; angle: string };
export type CompanyDemo = {
  id: CompanyDemoId; name: string; website: string; subtitle: string; headline: string; summary: string; companySources: string[]; product: string; customer: string; focus: string; geography: string; thesis: string;
  recommendations: string[]; markets: { name: string; rationale: string; tradeoff: string }[];
  icp: { title: string; items: string[] }[]; buyers: { role: string; responsibility: string; question: string }[];
  accounts: DemoAccount[]; ranking: string; limits: string;
  steps: { stage: string; exit: string }[]; measures: string[];
  campaigns: { title: string; channel: string; action: string; measure: string }[];
  insights: { title: string; why: string; action: string }[];
  sources: DemoSource[];
};
export const demoReviewed = "October 8, 2026";
const source = (id: string, title: string, publisher: string, url: string, date = "Undated live page", note?: string): DemoSource => ({ id, title, publisher, url, date, note });

export const companyDemos: CompanyDemo[] = [
  {
    id: "nike", name: "Nike", website: "https://www.nike.com", subtitle: "Consumer demand & retail partner growth", headline: "Turn product discovery into retail sell-through.",
    summary: "Nike sells athletic footwear, apparel and equipment. Its public reporting separates wholesale from NIKE Direct, which includes owned stores and digital commerce. Nike Running presents footwear, apparel and accessories across running disciplines.", companySources: ["nike-company", "nike-results", "nike-running"],
    product: "Performance footwear, apparel & equipment", customer: "Athletes and everyday consumers; retailers are channel accounts", focus: "U.S. running demand + selected retail partners", geography: "United States · proposed scope",
    thesis: "Use a small, jointly measured retail activation to connect running-product education with purchase. Treat retailers as existing distribution channels, while consumers remain the end customers.",
    recommendations: ["Start with DICK’S running assortment and one defined consumer need.", "Use JD Sports as a second, distinct footwear-discovery test.", "Agree on inventory, store scope and measurement before spending on demand."],
    markets: [
      { name: "Performance running · first test", rationale: "Nike’s running category provides a concrete product-education context. DICK’S publishes a Nike running assortment.", tradeoff: "A category page does not establish consumer demand or store-level availability." },
      { name: "Footwear discovery · second test", rationale: "JD Sports lists Nike footwear and apparel. A merchandising experiment can be framed around a selected consumer use case.", tradeoff: "Lifestyle engagement and performance-running conversion need separate measures." },
      { name: "Broad sporting-goods retail · later", rationale: "Academy lists Nike athletic footwear, making it a real channel candidate for a narrower follow-up.", tradeoff: "Do not expand before an initial activation shows incremental sell-through." },
    ],
    icp: [{ title: "Strong channel fit", items: ["Published Nike assortment", "A category owner and agreed retail scope", "Stock availability and access to sell-through data"] }, { title: "Strong consumer fit · hypothesis", items: ["A specific running need rather than a broad demographic", "Product education that helps selection", "A reachable local audience with a relevant purchase destination"] }, { title: "Defer", items: ["Unclear inventory or retailer approval", "Discount-only concepts without a margin view", "Campaigns measured only by impressions"] }],
    buyers: [{ role: "Retail category / footwear merchant", responsibility: "Proposed partner owner for assortment and merchandising.", question: "Which products and stores can participate?" }, { role: "Retail marketing lead", responsibility: "Proposed owner of activation and channel measurement.", question: "Can we compare incremental sales against a suitable baseline?" }, { role: "Nike account / marketplace lead", responsibility: "Proposed internal relationship owner.", question: "Does the concept fit the existing joint business plan?" }],
    accounts: [
      { id: "dicks", company: "DICK’S Sporting Goods", segment: "Sporting-goods retail", relationship: "Published Nike assortment · existing channel context", fact: "DICK’S advertises Nike running footwear for men, women and children.", sourceId: "dicks", why: "The clearest category-specific starting point for a running-product education test. This is partner development, not a claimed new-logo opportunity.", buyer: "Running / footwear category merchant", action: "Ask the existing account owner to select one product story, store cohort and inventory window.", constraint: "Confirm sell-through access, stock and partner approval; public assortment does not reveal wholesale terms.", question: "Which shopper need is least well served by the current running presentation?", angle: "A focused running-choice guide connected to available products and a measurable store or online destination." },
      { id: "jd", company: "JD Sports", segment: "Footwear & apparel retail", relationship: "Published Nike assortment · existing channel context", fact: "JD Sports’ Nike storefront lists shoes and clothing, including running and basketball footwear.", sourceId: "jd", why: "A distinct retail discovery context makes a useful second test. It should not inherit DICK’S consumer assumptions or success criteria.", buyer: "Nike footwear category / merchandising lead", action: "Review the existing account plan and propose a tightly scoped footwear-discovery placement.", constraint: "Confirm launch rights, merchandising space and measurement; a product listing is not evidence of a new commitment.", question: "Which product story needs clearer discovery without relying on discounting?", angle: "Pair product storytelling with a selected assortment and compare conversion with the current presentation." },
      { id: "academy", company: "Academy Sports + Outdoors", segment: "Sporting-goods retail", relationship: "Published Nike assortment · existing channel context", fact: "Academy’s athletic footwear catalog lists Nike training and running-style shoes.", sourceId: "academy", why: "A credible later channel test once the initial playbook and inventory requirements are understood.", buyer: "Athletic footwear merchant", action: "Validate category priorities through the relationship owner before proposing a pilot.", constraint: "Do not extrapolate local demand or store distribution from online assortment.", question: "Is there a category and store cluster with both available stock and a relevant consumer need?", angle: "A simple selection guide and store activation built around an agreed assortment." },
    ],
    ranking: "DICK’S comes first for direct running-category relevance; JD Sports is second for a different discovery context. Academy stays in the full list. This is editorial sequencing, not a retailer performance score.",
    limits: "Retail listings establish assortment, not exact supplier agreements, account health or willingness to run a campaign. Consumer demand, inventory, margins and the joint business plans require internal data.",
    steps: [{ stage: "Align the partner", exit: "Existing relationship owner and retailer category owner approve a specific scope." }, { stage: "Confirm readiness", exit: "Products, stock, stores, timing and baseline data are agreed." }, { stage: "Run the activation", exit: "Approved creative and retail placement go live with a comparison plan." }, { stage: "Measure and decide", exit: "Incremental sell-through and contribution justify scaling, revising or stopping." }],
    measures: ["Incremental sell-through", "Conversion by placement", "Availability / out-of-stock rate", "Contribution after activation cost"],
    campaigns: [{ title: "Find your running fit", channel: "Proposed DICK’S retail / digital test", action: "Explain an agreed running-use case, offer a product comparison and connect it to in-stock products. Set a comparison cohort before launch.", measure: "Incremental sell-through, conversion, returns and availability; use actual partner data." }, { title: "Discover the right footwear story", channel: "Proposed JD Sports merchandising test", action: "Test a focused product story against the current placement, keeping pricing and stock effects visible.", measure: "Conversion and contribution by placement, with consumer feedback on product selection." }],
    insights: [{ title: "The account is the channel; the consumer is the customer", why: "A wholesale account plan alone does not explain why a person chooses a Nike product.", action: "Connect every partner activation to one consumer need and purchase destination." }, { title: "Sell-through matters more than a bigger order", why: "A larger wholesale order can coexist with weak consumer demand or excess inventory.", action: "Make the pilot decision depend on stock-adjusted sales and economics." }, { title: "One playbook should not flatten every retailer", why: "Running selection and footwear discovery pose different merchandising questions.", action: "Use the same measurement discipline while tailoring the experience." }],
    sources: [source("nike-company", "Nike company overview", "NIKE, Inc.", "https://about.nike.com/en/company"), source("nike-results", "Fiscal 2027 Q1 results · channel definitions", "NIKE Investor Relations", "https://investors.nike.com/investors/news-events-and-reports/investor-news/investor-news-details/2026/NIKE-Inc--Reports-Fiscal-2027-First-Quarter-Results/default.aspx", "Fiscal 2027 Q1 release"), source("nike-running", "Nike Running category", "Nike", "https://www.nike.com/running"), source("dicks", "Nike running footwear assortment", "DICK’S Sporting Goods", "https://www.dickssportinggoods.com/f/nike-running-footwear", "Undated live catalog", "Search-index excerpt reviewed; full catalog text was unavailable to the research reader."), source("jd", "Nike storefront", "JD Sports", "https://www.jdsports.com/plp/nike"), source("academy", "Men’s athletic footwear catalog", "Academy Sports + Outdoors", "https://www.academy.com/c/mens/mens-footwear/mens-athletic-sneakers")],
  },
  {
    id: "decagon", name: "Decagon", website: "https://decagon.ai", subtitle: "Enterprise AI customer-experience sales", headline: "Sell one resolved workflow before a platform promise.",
    summary: "Decagon offers AI agents for customer experiences. Its Agent Operating Procedures let teams define workflows, connect support systems and set escalation rules. Its public customer-story directory includes Rippling, ClassPass and Substack; these are vendor-published references, not independent ROI audits.", companySources: ["decagon-home", "decagon-aop", "decagon-proof"],
    product: "AI agents for customer experience", customer: "CX teams with repeatable support workflows and controllable system access", focus: "Digital subscriptions & marketplaces · proposed wedge", geography: "English-language pilot · proposed scope",
    thesis: "Start with one bounded, policy-heavy support workflow. Prove correct resolution and safe escalation before expanding to more channels or more consequential actions.",
    recommendations: ["Prioritize Canva’s billing / subscription workflow hypothesis.", "Investigate Etsy’s order-status guidance as a second, tightly bounded use case.", "Qualify ownership, permissions and quality thresholds before discussing rollout."],
    markets: [{ name: "Digital subscriptions · first", rationale: "Canva and Duolingo publish subscription-support topics. Recurring policy questions provide a concrete discovery starting point.", tradeoff: "Public help pages do not reveal ticket volume, automation gaps or current vendors." }, { name: "Marketplaces · second", rationale: "Etsy’s help center covers buyers, sellers, orders and payments, showing distinct support journeys.", tradeoff: "Marketplace disputes and trust decisions require stricter boundaries than informational questions." }, { name: "Wider enterprise CX · later", rationale: "Decagon’s customer stories provide examples across several workflows and business models.", tradeoff: "Reference outcomes cannot be imported into another buyer’s business case." }],
    icp: [{ title: "Strong workflow fit · hypothesis", items: ["Repeatable questions governed by written policies", "A CX owner with a measurable baseline", "Permitted access to reliable support and account systems"] }, { title: "Pilot requirements", items: ["Approved evaluation set and escalation rules", "Human review for sensitive decisions", "A defined process for policy changes and incident handling"] }, { title: "Defer", items: ["No baseline or workflow owner", "Unbounded actions across customer accounts", "A buyer seeking only a generic chatbot without an operating plan"] }],
    buyers: [{ role: "VP / Head of Customer Experience", responsibility: "Proposed economic owner of service quality and cost.", question: "Which workflow is worth improving, and what would justify rollout?" }, { role: "Support operations lead", responsibility: "Proposed champion for policies, quality evaluation and escalations.", question: "Which resolutions can be safely automated under existing policy?" }, { role: "Engineering / security evaluator", responsibility: "Proposed owner of access controls, integration and data handling.", question: "What is the minimum permission scope and how do we revoke it?" }],
    accounts: [
      { id: "canva", company: "Canva", segment: "Design SaaS / subscriptions", relationship: "Research candidate · Decagon relationship unknown", fact: "Canva’s help center offers subscription management, charge explanations and account-recovery topics.", sourceId: "canva", why: "Subscription guidance is a specific, bounded starting workflow. Fit depends on unmet need, internal ownership and permitted data access—not the size of the brand.", buyer: "Head of Customer Support / CX Operations", action: "Check CRM ownership and existing providers, then ask for an anonymized billing-support sample and baseline.", constraint: "Do not assume Canva needs a new provider; avoid exposing customer data in a demo.", question: "Where do subscription questions still need a person after self-service?", angle: "Evaluate policy-grounded subscription guidance with explicit escalation for disputed charges." },
      { id: "etsy", company: "Etsy", segment: "Two-sided marketplace", relationship: "Research candidate · Decagon relationship unknown", fact: "Etsy’s help center separates shopping and selling topics, including order issues, returns, shipping and payments.", sourceId: "etsy", why: "Multiple support journeys make workflow segmentation relevant, but a safe first test should answer routine questions rather than decide disputes.", buyer: "Customer Support Operations / Member Experience lead", action: "Check account ownership, then validate one buyer order-status workflow with its policy owner.", constraint: "Exclude dispute adjudication, account enforcement and payment decisions from the initial proposal.", question: "Which order-status questions can be resolved without changing a transaction or judging a dispute?", angle: "A small order-guidance evaluation that keeps seller and buyer policies distinct." },
      { id: "duolingo", company: "Duolingo", segment: "Learning subscriptions", relationship: "Research candidate · Decagon relationship unknown", fact: "Duolingo’s public help topics include subscription cancellation and refund requests.", sourceId: "duolingo", why: "A narrower subscription-support candidate for later discovery after the first pilot pattern is proven.", buyer: "Head of Support / Subscriber Experience", action: "Validate channel ownership and current automation before drafting a cancellation-guidance evaluation.", constraint: "App-store and direct-web billing policies differ; do not imply an agent can approve every refund.", question: "How does the support flow identify the billing channel before applying policy?", angle: "Clear billing-channel guidance and handoff for exceptions, with resolution quality measured." },
    ],
    ranking: "Canva is first for a clear subscription-support hypothesis; Etsy is second for a different, bounded marketplace workflow. Duolingo remains a later candidate. Ranking reflects use-case specificity and pilot boundaries, not known demand or company performance.",
    limits: "These organizations are research candidates, not verified net-new prospects. Current Decagon relationships, support volume, incumbent vendors, budgets and decision-makers are unknown. Public support documentation establishes workflows, not pain intensity.",
    steps: [{ stage: "Qualify a workflow", exit: "Named owner, current process, unmet need and baseline are confirmed." }, { stage: "Pass evaluation and access review", exit: "Approved data, limited permissions, test cases and escalation criteria are agreed." }, { stage: "Run a bounded pilot", exit: "Correct resolution and failures are reviewed against the baseline." }, { stage: "Earn expansion", exit: "The buyer accepts quality, operating cost and ownership before wider rollout." }],
    measures: ["Correct resolution rate", "Escalation quality", "Customer satisfaction", "Cost per resolved case"],
    campaigns: [{ title: "Workflow teardown workshop", channel: "Proposed account-specific discovery", action: "Use public help topics to draft an example; ask the buyer to correct it before requesting approved evaluation data.", measure: "Confirmed workflow owner, accepted evaluation scope and baseline access." }, { title: "Bounded evaluation offer", channel: "Proposed technical / CX working session", action: "Compare a permitted workflow with the current process using an agreed test set and explicit failure criteria.", measure: "Correct resolution, unsafe-action rate, escalation completeness and buyer acceptance." }],
    insights: [{ title: "A help center is a clue, not proof of pain", why: "Published billing topics do not prove high contact volume or a failing current solution.", action: "Make discovery validate the actual workload and vendor landscape." }, { title: "Deflection alone can reward bad service", why: "A customer who gives up is not a successful resolution.", action: "Evaluate resolution correctness and customer experience alongside cost." }, { title: "Expansion requires an operating owner", why: "Policies and workflows keep changing after the pilot.", action: "Agree on evaluation, change approval and incident response before rollout." }],
    sources: [source("decagon-home", "Decagon product overview", "Decagon", "https://decagon.ai/"), source("decagon-aop", "Agent Operating Procedures", "Decagon", "https://decagon.ai/product/aop"), source("decagon-proof", "Customer-story directory", "Decagon", "https://decagon.ai/case-studies", "Undated live page", "Vendor-published customer references; outcomes are not independently audited here."), source("canva", "Canva Help Center", "Canva", "https://www.canva.com/help/"), source("etsy", "Shopping and selling support", "Etsy", "https://help.etsy.com/hc/en-us"), source("duolingo", "Duolingo Help Center", "Duolingo", "https://www.duolingo.com/help", "Undated live page", "Search-index help topics reviewed; full page text was unavailable to the research reader.")],
  },
  {
    id: "anduril", name: "Anduril", website: "https://www.anduril.com", subtitle: "Public-program procurement & account development", headline: "Build a credible path from program evidence to delivery.",
    summary: "Anduril develops defense technology, including Lattice software and autonomous systems. Its public announcements describe U.S. Air Force and U.S. Navy programs. Australia’s Defence Ministry confirms a Ghost Shark contract covering delivery, maintenance and continued development.", companySources: ["anduril-lattice", "airforce", "navy", "australia"],
    product: "Defense software & autonomous systems", customer: "Government program offices and authorized procurement stakeholders", focus: "Existing public programs · delivery and sustainment", geography: "United States & Australia · public-program scope",
    thesis: "Treat the published programs as established relationships to develop, not cold prospects. Start with delivery readiness, support and the authorized procurement path; expansion needs a validated requirement and approval.",
    recommendations: ["Prioritize Australia’s Ghost Shark delivery and sustainment context.", "Use the U.S. Air Force program as a second account-development focus.", "Keep the Navy program in the wider list until its current stage and ownership are confirmed."],
    markets: [{ name: "Australian maritime programs · first", rationale: "Australia’s Defence Ministry confirms a multi-year Ghost Shark delivery and support agreement.", tradeoff: "A public contract does not reveal remaining scope, supplier capacity or a new approved requirement." }, { name: "U.S. aviation programs · second", rationale: "Anduril publicly describes a U.S. Air Force Collaborative Combat Aircraft production contract.", tradeoff: "Published selection is not proof of acceptance, future orders or a new sales opportunity." }, { name: "U.S. maritime programs · monitor", rationale: "Anduril reports selection with DIU and the U.S. Navy for an XL-AUV program.", tradeoff: "Demonstration, production and sustainment are distinct procurement stages." }],
    icp: [{ title: "Strong program fit · hypothesis", items: ["A public requirement relevant to an offered product", "An authorized program and procurement owner", "An accepted evaluation and delivery pathway"] }, { title: "Expansion requirements", items: ["Documented unmet requirement within authorized scope", "Validated acquisition route and approvals", "Delivery capacity and a sustainment plan"] }, { title: "Defer", items: ["Unverified budget or informal interest", "A proposed export without required approvals", "A logo-based forecast without a contract or accepted next step"] }],
    buyers: [{ role: "Program manager / capability sponsor", responsibility: "Proposed owner of requirement and acceptance criteria.", question: "What publicly discussable delivery or support requirement remains unmet?" }, { role: "Contracting / acquisition officer", responsibility: "Proposed owner of the authorized commercial process.", question: "Which procurement route and approvals apply?" }, { role: "Integration / sustainment lead", responsibility: "Proposed evaluator of delivery readiness and ongoing support.", question: "What evidence is required for acceptance and support readiness?" }],
    accounts: [
      { id: "australia", company: "Australian Department of Defence", segment: "Ghost Shark / Royal Australian Navy", relationship: "Confirmed public contract · existing program context", fact: "On September 10, 2025, Australia’s Defence Ministry announced a five-year Anduril Australia contract for Ghost Shark delivery, maintenance and continued development.", sourceId: "australia", why: "The public agreement explicitly includes support as well as delivery, making lifecycle account planning a concrete starting point.", buyer: "Authorized Ghost Shark program / acquisition owner", action: "Through the established relationship owner, review approved delivery and sustainment milestones and identify any validated support gap.", constraint: "Do not treat the announced contract as new pipeline or infer additional funding; confirm current scope internally.", question: "Which acceptance or support milestone needs clearer ownership or evidence?", angle: "An account-development review of delivery readiness, support ownership and agreed acceptance evidence." },
      { id: "airforce", company: "U.S. Department of the Air Force", segment: "Collaborative Combat Aircraft program", relationship: "Company-reported public contract · existing program context", fact: "Anduril’s public announcement describes a production contract for the U.S. Air Force Collaborative Combat Aircraft program.", sourceId: "airforce", why: "A named procurement program is a better account-development anchor than a generic defense-market thesis.", buyer: "Authorized CCA program / acquisition owner", action: "Validate the current contract stage and approved acceptance process with the internal program owner before proposing follow-on support work.", constraint: "Contract announcement, delivery and acceptance are different facts. No additional award or funding is assumed.", question: "What approved acceptance and support evidence must be complete for the next program milestone?", angle: "A program-readiness discussion focused on acceptance documentation and support responsibilities." },
      { id: "navy", company: "U.S. Navy / Defense Innovation Unit", segment: "XL-AUV public program", relationship: "Company-reported selection · existing program context", fact: "Anduril publicly reports that DIU and the U.S. Navy selected it for an XL-AUV program involving Dive-XL.", sourceId: "navy", why: "A relevant maritime relationship to monitor, with current demonstration and acquisition stages requiring confirmation.", buyer: "Authorized maritime program / contracting owner", action: "Confirm program status through the established account owner and document the next approved evaluation gate.", constraint: "Do not equate prototype selection with fleet production, contracted revenue or future orders.", question: "Which evaluation gate has been formally accepted, and what is the next authorized step?", angle: "Clarify the agreed evaluation pathway and evidence required before any expansion discussion." },
    ],
    ranking: "Australia comes first because delivery and maintenance are explicitly in the government’s public agreement. Air Force is second for a named production-program context. Navy stays in the full list pending stage confirmation. This is editorial account-development priority, not a capability comparison or win probability.",
    limits: "This case uses public, unclassified commercial context only. Current contract performance, acceptance status, program budgets, authorized contacts and follow-on scope are unknown. Company announcements are attributed and do not independently verify program outcomes.",
    steps: [{ stage: "Validate the requirement", exit: "An authorized program owner confirms a specific requirement within approved scope." }, { stage: "Confirm the acquisition route", exit: "Contracting authority, applicable approvals and evaluation pathway are established." }, { stage: "Document readiness", exit: "The buyer accepts delivery, integration and sustainment evidence." }, { stage: "Qualify additional scope", exit: "A distinct approved requirement and commercial next step exist; an announcement alone is insufficient." }],
    measures: ["Accepted program milestones", "Delivery readiness", "Support readiness", "Approved follow-on scope"],
    campaigns: [{ title: "Program-readiness review", channel: "Proposed existing-account working session", action: "Review publicly discussable acceptance milestones, commercial ownership and support responsibilities with authorized stakeholders.", measure: "Agreed milestone owners and documented acceptance requirements." }, { title: "Sustainment planning brief", channel: "Proposed authorized procurement discussion", action: "Separate current contracted support from any additional requirement and confirm its acquisition pathway before proposing scope.", measure: "Validated support requirement, approvals and an accepted next step." }],
    insights: [{ title: "These are established programs, not cold logos", why: "Public announcements already establish relationships, so a net-new prospect list would misrepresent the facts.", action: "Frame the work around program delivery and account development." }, { title: "A contract announcement is not revenue recognized", why: "Public awards do not disclose all delivery, acceptance or accounting details.", action: "Keep private pipeline and revenue unknown; avoid importing award values into forecasts." }, { title: "Procurement is part of the value proposition", why: "A plausible product fit still needs an authorized acquisition path and support plan.", action: "Qualify governance, ownership and readiness before proposing additional scope." }],
    sources: [source("anduril-lattice", "Lattice for Command & Control", "Anduril", "https://www.anduril.com/lattice/command-and-control", "Undated live page", "Publisher search-index excerpt reviewed; full body was unavailable to the research reader."), source("australia", "Ghost Shark delivery and support contract", "Australian Defence Ministry", "https://www.minister.defence.gov.au/media-releases/2025-09-10/equipping-royal-australian-navy-next-generation-autonomous-undersea-vehicles", "September 10, 2025"), source("airforce", "U.S. Air Force CCA production contract", "Anduril", "https://www.anduril.com/news/anduril-wins-production-contract-for-u-s-air-force-cca-program", "2026 announcement", "Company-reported; publisher search-index excerpt reviewed. Full body was unavailable to the research reader."), source("navy", "DIU and U.S. Navy XL-AUV selection", "Anduril", "https://www.anduril.com/news/diu-and-u-s-navy-select-anduril-for-xl-auv-program", "March 2026 announcement", "Company-reported; publisher search-index excerpt reviewed. Full body was unavailable to the research reader.")],
  },
];

export function demoPlan(demo: CompanyDemo): GTMPlan {
  return { id: `research-${demo.id}`, createdAt: "2026-10-08T00:00:00Z", isDemo: false, generationMode: "demo", input: { company: demo.name, website: demo.website, product: demo.product, targetMarket: demo.customer, geography: demo.geography, goal: demo.focus }, summary: demo.summary, valueProposition: demo.thesis, positioning: demo.thesis, segments: [], icp: { strong: [], moderate: [], weak: [] }, personas: [], accounts: [], campaigns: [], messaging: { painPoints: [], proofPoints: [], coldEmail: "", linkedIn: "", callOpener: "", elevatorPitch: "", discoveryQuestions: [], objections: [] }, recommendations: demo.recommendations, insights: [] };
}
export function visibleSavedProjects(projects: GTMPlan[]) {
  return projects.filter(({ input }) => !/^(forecast\s*flow|sentinel(?:\s*ai)?)$/i.test(input.company.trim()));
}
